# Generated by Django 2.1.5 on 2020-08-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(default='37,5|38,5|39|39,5|40|41|41,5|42|43|43,5|44|44,5|45|46|46,5|47'),
        ),
    ]
