# Generated by Django 2.1.5 on 2020-08-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200815_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='No Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True),
        ),
    ]
