# Generated by Django 2.1.5 on 2020-08-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200815_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('size', models.TextField()),
                ('image', models.TextField()),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cart')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Category'),
        ),
    ]
