# Generated by Django 2.1.5 on 2020-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200815_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttocart',
            name='image',
            field=models.ImageField(upload_to='mediaa/'),
        ),
    ]
