# Generated by Django 2.1.5 on 2020-08-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200815_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttocart',
            name='cart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='productto', to='main.Cart'),
        ),
    ]
