# Generated by Django 2.1.5 on 2020-08-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200816_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('massage', models.CharField(blank=True, max_length=250)),
                ('paymant', models.CharField(choices=[('Cash', 'Наличные'), ('Credit', 'Банковский перевод')], max_length=250)),
                ('addres', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
