# Generated by Django 2.1.5 on 2020-08-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200828_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
