# Generated by Django 2.1.5 on 2020-08-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200828_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Some Description'),
        ),
    ]
